In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score,RandomizedSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,accuracy_score, precision_score, recall_score,f1_score,make_scorer
from sklearn.model_selection import GridSearchCV

In [2]:
data = pd.read_csv("serieb_modelagem.csv")

In [3]:
data.head()

idteamgame     idopponentgame  ...  opp_tackles_won opp_own_goals
0   Bragantino_6.0_2019   Vitória_6.0_2019  ...             13.0           1.0
1   Bragantino_9.0_2019    Paraná_9.0_2019  ...             10.2           0.0
2  Bragantino_10.0_2019    Oeste_10.0_2019  ...             10.8           0.0
3  Bragantino_13.0_2019   Cuiabá_13.0_2019  ...             13.8           0.0
4  Bragantino_14.0_2019  Guarani_14.0_2019  ...             12.2           0.0

[5 rows x 45 columns]

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2070 entries, 0 to 2069
Data columns (total 45 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   idteamgame                     2070 non-null   object 
 1   idopponentgame                 2070 non-null   object 
 2   tournament                     2070 non-null   int64  
 3   venue                          2070 non-null   int64  
 4   result                         2070 non-null   object 
 5   points                         2070 non-null   float64
 6   possession                     2070 non-null   float64
 7   gdiff                          2070 non-null   float64
 8   shots                          2070 non-null   float64
 9   p_shotsontarget                2070 non-null   float64
 10  goals_shots                    2070 non-null   float64
 11  penalty_goals                  2070 non-null   float64
 12  p_penaltyconverted             2070 non-null   f

In [3]:
data['venue'] = data['venue'].replace(['Home','Away'],[1,0])
data = data.drop(columns=['idteamgame','idopponentgame','tournament'])

### 1. Tipo 1 - Todas as variaveis

In [18]:
X = data.drop(columns=['result'])
y = data['result']

In [19]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=325)

X_test,X_val,y_test,y_val = train_test_split(X_test,y_test,test_size=0.5, random_state=3255)

In [20]:
# Dados
print("Total")
print(len(X.index))
print(len(y.index))

# Treino e Teste (geral)
print("Treino")
print(len(X_train.index))
print(len(y_train.index))

print("Teste")
print(len(X_test.index))
print(len(y_test.index))

print("Validação")
print(len(X_val.index))
print(len(y_val.index))

Total
2070
2070
Treino
1449
1449
Teste
310
310
Validação
311
311


In [21]:
model_1 = RandomForestClassifier()
model_1.fit(X_train,y_train)

RandomForestClassifier()

In [22]:
predictions_1 = model_1.predict(X_test)

In [28]:
print("Confusion Matrix")
print(confusion_matrix(y_test,predictions_1))
print("Accuracy:",accuracy_score(y_test,predictions_1))
print("Precision:",precision_score(y_test,predictions_1,average='weighted'))
print("Sensitivity:",recall_score(y_test,predictions_1,average='weighted')) #Sensitivity
print("Specifity:",recall_score(y_test,predictions_1,pos_label=0,average='weighted')) #Specifity
print("F1-Score:",f1_score(y_test,predictions_1,average='weighted'))

Confusion Matrix
[[11 36 30]
 [23 51 26]
 [30 36 67]]
Accuracy: 0.4161290322580645
Precision: 0.4101449809861002
Sensitivity: 0.4161290322580645
Specifity: 0.4161290322580645
F1-Score: 0.4108751039066596


In [30]:
predictions_2 = model_1.predict(X_val)

In [32]:
print("Confusion Matrix")
print(confusion_matrix(y_val,predictions_2))
print("Accuracy:",accuracy_score(y_val,predictions_2))
print("Precision:",precision_score(y_val,predictions_2,average='weighted'))
print("Sensitivity:",recall_score(y_val,predictions_2,average='weighted')) #Sensitivity
print("Specifity:",recall_score(y_val,predictions_2,pos_label=0,average='weighted')) #Specifity
print("F1-Score:",f1_score(y_val,predictions_2,average='weighted'))

Confusion Matrix
[[22 43 32]
 [16 65 30]
 [17 46 40]]
Accuracy: 0.40836012861736337
Precision: 0.4052823350913005
Sensitivity: 0.40836012861736337
Specifity: 0.40836012861736337
F1-Score: 0.3946202556537614


### 2. Tipo 2 - subtrair variáveis

In [4]:
data_2 = data

In [5]:
data_2['points'] = data_2['points'] - data_2['opp_points']
data_2['possession'] = data_2['possession'] - data_2['opp_possession']
data_2['gdiff'] = data_2['gdiff'] - data_2['opp_gdiff']
data_2['shots'] = data_2['shots'] - data_2['opp_shots']
data_2['p_shotsontarget'] = data_2['p_shotsontarget'] - data_2['opp_p_shotsontarget']
data_2['goals_shots'] = data_2['goals_shots'] - data_2['opp_goals_shots']
data_2['penalty_goals'] = data_2['penalty_goals'] - data_2['opp_penalty_goals']
data_2['p_penaltyconverted'] = data_2['p_penaltyconverted'] - data_2['opp_p_penaltyconverted']
data_2['shotsontarget_against'] = data_2['shotsontarget_against'] - data_2['opp_shotsontarget_against']
data_2['p_saves'] = data_2['p_saves'] - data_2['opp_p_saves']
data_2['cleansheets'] = data_2['cleansheets'] - data_2['opp_cleansheets']
data_2['penalty_attempted_against'] = data_2['penalty_attempted_against'] - data_2['opp_penalty_attempted_against']
data_2['p_penalty_saved'] = data_2['p_penalty_saved'] - data_2['opp_p_penalty_saved']
data_2['cardscore'] = data_2['cardscore'] - data_2['opp_cardscore']
data_2['foulsdiff'] = data_2['foulsdiff'] - data_2['opp_foulsdiff']
data_2['offsides'] = data_2['offsides'] - data_2['opp_offsides']
data_2['crosses'] = data_2['crosses'] - data_2['opp_crosses']
data_2['interceptions'] = data_2['interceptions'] - data_2['opp_interceptions']
data_2['tackles_won'] = data_2['tackles_won'] - data_2['opp_tackles_won']
data_2['own_goals'] = data_2['own_goals'] - data_2['opp_own_goals']

In [6]:
data_2 = data_2.iloc[:,0:22]

In [7]:
X = data_2.drop(columns=['result'])
y = data_2['result']

In [71]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=325)

X_test,X_val,y_test,y_val = train_test_split(X_test,y_test,test_size=0.5, random_state=3255)

In [72]:
model_1 = RandomForestClassifier(criterion='log_loss', max_depth=4, max_features=None)
model_1.fit(X_train,y_train)

RandomForestClassifier(criterion='log_loss', max_depth=4, max_features=None)

In [73]:
predictions_1 = model_1.predict(X_test)

In [74]:
print("Confusion Matrix")
print(confusion_matrix(y_test,predictions_1))
print("Accuracy:",accuracy_score(y_test,predictions_1))
print("Precision:",precision_score(y_test,predictions_1,average='weighted'))
print("Sensitivity:",recall_score(y_test,predictions_1,average='weighted')) #Sensitivity
print("Specifity:",recall_score(y_test,predictions_1,pos_label=0,average='weighted')) #Specifity
print("F1-Score:",f1_score(y_test,predictions_1,average='weighted'))

Confusion Matrix
[[ 7 33 37]
 [ 5 63 32]
 [ 1 51 81]]
Accuracy: 0.4870967741935484
Precision: 0.5036731655441333
Sensitivity: 0.4870967741935484
Specifity: 0.4870967741935484
F1-Score: 0.4487877391778716


In [61]:
predictions_2 = model_1.predict(X_val)

In [62]:
print("Confusion Matrix")
print(confusion_matrix(y_val,predictions_2))
print("Accuracy:",accuracy_score(y_val,predictions_2))
print("Precision:",precision_score(y_val,predictions_2,average='weighted'))
print("Sensitivity:",recall_score(y_val,predictions_2,average='weighted')) #Sensitivity
print("Specifity:",recall_score(y_val,predictions_2,pos_label=0,average='weighted')) #Specifity
print("F1-Score:",f1_score(y_val,predictions_2,average='weighted'))

Confusion Matrix
[[27 38 32]
 [19 55 37]
 [27 39 37]]
Accuracy: 0.38263665594855306
Precision: 0.37967698558664426
Sensitivity: 0.38263665594855306
Specifity: 0.38263665594855306
F1-Score: 0.37790217944585325


### 3 - Subtraindo valores e considerando apenas o time da casa

In [79]:
data_3 = data_2[data_2['venue'] == 1]
data_3 = data_3.drop(columns=['venue'])

In [80]:
data_3.head()

result  points  possession  ...  interceptions  tackles_won  own_goals
3       D   -22.0      -1.278  ...          -24.8        -45.8        0.0
5       W   -24.0      -1.080  ...          -35.8        -33.6        0.0
7       D   -44.0      -1.332  ...          -35.6        -37.4        0.0
9       W    -4.0      -1.684  ...          -17.6        -44.4        0.0
11      W   -10.0      -1.456  ...          -37.4        -28.0        0.0

[5 rows x 21 columns]

In [81]:
X = data_3.drop(columns=['result'])
y = data_3['result']

In [82]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=325)

X_test,X_val,y_test,y_val = train_test_split(X_test,y_test,test_size=0.5, random_state=3255)

In [96]:
model_1 = RandomForestClassifier()
model_1.fit(X_train,y_train)

RandomForestClassifier()

In [97]:
predictions_1 = model_1.predict(X_test)

In [98]:
print("Confusion Matrix")
print(confusion_matrix(y_test,predictions_1))
print("Accuracy:",accuracy_score(y_test,predictions_1))
print("Precision:",precision_score(y_test,predictions_1,average='weighted'))
print("Sensitivity:",recall_score(y_test,predictions_1,average='weighted')) #Sensitivity
print("Specifity:",recall_score(y_test,predictions_1,pos_label=0,average='weighted')) #Specifity
print("F1-Score:",f1_score(y_test,predictions_1,average='weighted'))

Confusion Matrix
[[12  6 33]
 [ 9  3 28]
 [15  3 46]]
Accuracy: 0.3935483870967742
Precision: 0.351703346397347
Sensitivity: 0.3935483870967742
Specifity: 0.3935483870967742
F1-Score: 0.34269095916540443


In [99]:
predictions_2 = model_1.predict(X_val)

In [100]:
print("Confusion Matrix")
print(confusion_matrix(y_val,predictions_2))
print("Accuracy:",accuracy_score(y_val,predictions_2))
print("Precision:",precision_score(y_val,predictions_2,average='weighted'))
print("Sensitivity:",recall_score(y_val,predictions_2,average='weighted')) #Sensitivity
print("Specifity:",recall_score(y_val,predictions_2,pos_label=0,average='weighted')) #Specifity
print("F1-Score:",f1_score(y_val,predictions_2,average='weighted'))

Confusion Matrix
[[ 5  4 42]
 [ 9  5 28]
 [ 7  1 54]]
Accuracy: 0.4129032258064516
Precision: 0.38801843317972345
Sensitivity: 0.4129032258064516
Specifity: 0.4129032258064516
F1-Score: 0.330066170388751


### 4 - SUbstraindo e considerando vitoria/nao vitoria

In [8]:
data_2['result'] = data_2['result'].replace(['W','D','L'],[1,0,0])

In [10]:
X = data_2.drop(columns=['result'])
y = data_2['result']

In [11]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=325)

X_test,X_val,y_test,y_val = train_test_split(X_test,y_test,test_size=0.5, random_state=3255)

In [12]:
model_1 = RandomForestClassifier()
model_1.fit(X_train,y_train)

RandomForestClassifier()

In [13]:
predictions_1 = model_1.predict(X_test)

In [14]:
print("Confusion Matrix")
print(confusion_matrix(y_test,predictions_1))
print("Accuracy:",accuracy_score(y_test,predictions_1))
print("Precision:",precision_score(y_test,predictions_1,average='weighted'))
print("Sensitivity:",recall_score(y_test,predictions_1,average='weighted')) #Sensitivity
print("Specifity:",recall_score(y_test,predictions_1,pos_label=0,average='weighted')) #Specifity
print("F1-Score:",f1_score(y_test,predictions_1,average='weighted'))

Confusion Matrix
[[162  15]
 [111  22]]
Accuracy: 0.5935483870967742
Precision: 0.5939162842388649
Sensitivity: 0.5935483870967742
Specifity: 0.5935483870967742
F1-Score: 0.5221404174573056


In [15]:
predictions_2 = model_1.predict(X_val)

In [16]:
print("Confusion Matrix")
print(confusion_matrix(y_val,predictions_2))
print("Accuracy:",accuracy_score(y_val,predictions_2))
print("Precision:",precision_score(y_val,predictions_2,average='weighted'))
print("Sensitivity:",recall_score(y_val,predictions_2,average='weighted')) #Sensitivity
print("Specifity:",recall_score(y_val,predictions_2,pos_label=0,average='weighted')) #Specifity
print("F1-Score:",f1_score(y_val,predictions_2,average='weighted'))

Confusion Matrix
[[189  19]
 [ 88  15]]
Accuracy: 0.6559485530546624
Precision: 0.6024493700576101
Sensitivity: 0.6559485530546624
Specifity: 0.6559485530546624
F1-Score: 0.5937816229316174


### 5 - Tentando melhorar o modelo

In [93]:
# Randomized Search
param_dist = {"criterion": ['gini', 'entropy', 'log_loss'],
              "max_depth":[4,6,8,None],
              "max_features":['sqrt', 'log2', None]}

In [94]:
random_search = RandomizedSearchCV(estimator=model_1, param_distributions=param_dist,n_iter=40,cv=5)

In [65]:
random_search.fit(X,y)

KeyboardInterrupt: 

In [66]:
random_search.best_estimator_

RandomForestClassifier(criterion='log_loss', max_depth=4, max_features=None)